/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jlanches.src.views.internal.frame.advanced.search;

import com.jlanches.src.constants.Reports;
import com.jlanches.src.dao.ClienteDAO;
import com.jlanches.src.dao.FuncionarioDAO;
import com.jlanches.src.dao.PedidoDAO;
import com.jlanches.src.helpers.DateHelper;
import com.jlanches.src.helpers.FrameHelper;
import com.jlanches.src.helpers.ReportHelper;
import com.jlanches.src.model.Cliente;
import com.jlanches.src.model.Funcionario;
import com.jlanches.src.model.views.PedidoViewModel;
import com.jlanches.src.views.extension.elements.ComboItem;
import com.jlanches.src.views.extension.elements.DatePicker;
import static com.jlanches.src.views.extension.elements.DatePicker.ParseDate;
import java.util.HashMap;

/**
 *
 * @author arthur
 */
public class SearchPedido extends javax.swing.JFrame {
    
    public static class QueryModel{
        public String dataInicio;
        public String dataFim;
        public Cliente cliente;
        public Funcionario funcionario;
    }
    
    public static class QueryMaker{
        public String getQuery(QueryModel model){
            String selectData = "";
            String selectCliente = "";
            String selectFuncionario = "";
            if(!model.dataInicio.equals("") && !model.dataFim.equals("")){
                selectData = "("
                    + "pedido.data "
                    + "BETWEEN '"
                    + model.dataInicio
                    +"' AND '" + model.dataFim +"'"
                    + ") AND";
            }else if(!model.dataInicio.equals("")){
                selectData = " pedido.data >= '" + model.dataInicio + "' AND ";
            }else if(!model.dataFim.equals("")){
                selectData = " poedido.data <= '" + model.dataFim + "' AND ";
            }else{
                selectData = "";
            }
            
            if(model.cliente != null && !model.cliente.cpf.equals(""))
                selectCliente = " pedido.cliente_cpf LIKE '" 
                        + model.cliente.cpf.replace(".", "").replace("-", "").replace(" ", "") + "'";
            if(model.funcionario != null && !model.funcionario.cpf.equals(""))
                selectFuncionario = " pedido.funcionario_cpf LIKE '" 
                        + model.funcionario.cpf.replace(".", "").replace("-", "").replace(" ", "") + "'";
            
            if(!selectFuncionario.equals("") && !selectCliente.equals(""))
                selectCliente = selectCliente + " AND ";
            
            if(selectData.equals("") && selectCliente.equals("") && selectFuncionario.equals(""))
                return "";
            return " WHERE " + selectData + selectCliente + selectFuncionario;
        }
    }
    

    private PedidoViewModel view;
    private ParseDate dataInicio;
    private ParseDate dataFim;
    
    public SearchPedido(PedidoViewModel view) {
        this();
        this.view = view;
    }
    
    /**
     * Creates new form SearchPedido
     */
    public SearchPedido() {
        FrameHelper.setLookAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        this.dataInicio = new ParseDate(this.campoDataInicio);
        this.dataFim = new ParseDate(this.campoDataFim);
        new ClienteDAO().fillCombo(this.selectCliente);
        new FuncionarioDAO().fillCombo(this.selectFuncionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoDataInicio = new javax.swing.JTextField();
        btnSetDataInicio = new javax.swing.JButton();
        btnSetDataInicioAsAtual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        campoDataFim = new javax.swing.JTextField();
        btnSetDataFim = new javax.swing.JButton();
        btnSetDataFimAsAtual = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        selectCliente = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        selectFuncionario = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        btnLimparData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data de Início"));
        jPanel2.setToolTipText("");

        campoDataInicio.setText("jTextField1");

        btnSetDataInicio.setText("Selecionar data");
        btnSetDataInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSetDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDataInicioActionPerformed(evt);
            }
        });

        btnSetDataInicioAsAtual.setText("Data atual");
        btnSetDataInicioAsAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSetDataInicioAsAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDataInicioAsAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoDataInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetDataInicioAsAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSetDataInicioAsAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(campoDataInicio)
                    .addComponent(btnSetDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data de Fim"));
        jPanel3.setToolTipText("");

        campoDataFim.setText("jTextField1");

        btnSetDataFim.setText("Selecionar data");
        btnSetDataFim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSetDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDataFimActionPerformed(evt);
            }
        });

        btnSetDataFimAsAtual.setText("Data atual");
        btnSetDataFimAsAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSetDataFimAsAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDataFimAsAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoDataFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetDataFimAsAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSetDataFimAsAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(campoDataFim)
                    .addComponent(btnSetDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cliente"));

        selectCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        selectCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Funcionário"));

        selectFuncionario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        selectFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jlanches/media/icons/icons8-cancelar-64.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jlanches/media/icons/icons8-apagador-64.png"))); // NOI18N
        btnClear.setText("Limpar");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jlanches/media/icons/icons8-pesquisar-64.png"))); // NOI18N
        btnSearch.setText("Pesquisar");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnGenerateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jlanches/media/icons/icons8-pdf-2-64.png"))); // NOI18N
        btnGenerateReport.setText("Gerar relatório");
        btnGenerateReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        btnLimparData.setText("Não filtrar por data");
        btnLimparData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparData, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnLimparData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        QueryModel query = new QueryModel();
        query.dataInicio = this.dataInicio.getData();
        query.dataFim = this.dataFim.getData();
        String aux = ((ComboItem)this.selectCliente.getSelectedItem()).cpf != null ? (((ComboItem)this.selectCliente.getSelectedItem()).cpf) : "";
        query.cliente = 
                !aux.equals("") 
                    ? new ClienteDAO().get(aux) 
                    : null;
        aux = (((ComboItem)this.selectFuncionario.getSelectedItem()).cpf);
        query.funcionario = !aux.equals("") ? new FuncionarioDAO().get(aux) : null;
        
        String sql = new QueryMaker().getQuery(query);
        System.out.println(sql);
        new PedidoDAO().fillTableGeneric(this.view.tabelaPedidos, sql);
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLimparDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDataActionPerformed
        this.campoDataInicio.setText("");
        this.campoDataFim.setText("");
    }//GEN-LAST:event_btnLimparDataActionPerformed

    private void btnSetDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDataInicioActionPerformed
        new DatePicker(this.dataInicio).setVisible(true);
    }//GEN-LAST:event_btnSetDataInicioActionPerformed

    private void btnSetDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDataFimActionPerformed
        new DatePicker(this.dataFim).setVisible(true);
    }//GEN-LAST:event_btnSetDataFimActionPerformed

    private void btnSetDataInicioAsAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDataInicioAsAtualActionPerformed
        this.dataInicio.setData(new DatePicker.InternalDateHelper().getNow());
    }//GEN-LAST:event_btnSetDataInicioAsAtualActionPerformed

    private void btnSetDataFimAsAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDataFimAsAtualActionPerformed
        this.dataFim.setData(new DatePicker.InternalDateHelper().getNow());
    }//GEN-LAST:event_btnSetDataFimAsAtualActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        HashMap<String, String> hash = new HashMap<String, String>();
        QueryModel query = new QueryModel();
        query.dataInicio = this.dataInicio.getData();
        query.dataFim = this.dataFim.getData();
        String aux = ((ComboItem)this.selectCliente.getSelectedItem()).cpf != null ? (((ComboItem)this.selectCliente.getSelectedItem()).cpf) : "";
        query.cliente = 
                !aux.equals("") 
                    ? new ClienteDAO().get(aux) 
                    : null;
        aux = (((ComboItem)this.selectFuncionario.getSelectedItem()).cpf);
        query.funcionario = !aux.equals("") ? new FuncionarioDAO().get(aux) : null;
        
        String sql = new QueryMaker().getQuery(query).replace("pedido", "pedido_w");
        
        hash.put("query", sql);
        hash.put("header_message", "Pedidos "
                + (!query.dataInicio.equals("") && !query.dataFim.equals("") 
                        ? "realizados entre " + query.dataInicio + " e " + query.dataFim + " "
                        :(
                                !query.dataInicio.equals("") ? "realizados a partir de " + query.dataInicio + " "
                                        : (!query.dataFim.equals("") ? "realizados antes de " + query.dataFim + " " : "")
                   ))
                + ( query.cliente != null && !query.cliente.cpf.equals("") ? "feitos pelo cliente " + query.cliente.nome + " " : "")
                + ( query.funcionario != null && query.funcionario.cpf.equals("") ? " cadastrados pelo funcionário " + query.funcionario.nome + " " : "")
        );
        
        ReportHelper.showReport(Reports.PEDIDO_GENERICO, hash);
        
        this.dispose();
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.dataFim.clearData();
        this.dataInicio.clearData();
        this.selectCliente.setSelectedIndex(0);
        this.selectFuncionario.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnLimparData;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSetDataFim;
    private javax.swing.JButton btnSetDataFimAsAtual;
    private javax.swing.JButton btnSetDataInicio;
    private javax.swing.JButton btnSetDataInicioAsAtual;
    private javax.swing.JTextField campoDataFim;
    private javax.swing.JTextField campoDataInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> selectCliente;
    private javax.swing.JComboBox<String> selectFuncionario;
    // End of variables declaration//GEN-END:variables
}
