/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jlanches.src.views.internal.frame.advanced.add.item;

import com.jlanches.src.dao.ClienteDAO;
import com.jlanches.src.dao.LancheDAO;
import com.jlanches.src.helpers.ComboHelper;
import java.util.ArrayList;
import com.jlanches.src.helpers.FrameHelper;
import com.jlanches.src.helpers.MessageHelper;
import com.jlanches.src.model.Lanche;
import com.jlanches.src.model.LanchePedido;
import com.jlanches.src.model.Pedido;
import com.jlanches.src.model.views.AddItemPedidoModel;
import com.jlanches.src.model.views.PedidoFormModel;
import com.jlanches.src.views.extension.elements.ComboItem;
import com.jlanches.src.views.internal.frame.helpers.AddItemPedidoHelper;
import com.jlanches.src.views.internal.frame.helpers.PedidoFormHelper;
import java.text.DecimalFormat;
import javax.swing.JTable;

/**
 *
 * @author arthur
 */
public class AddItemPedido extends javax.swing.JFrame {

    private AddItemPedidoModel addItemPedido;
    private int index = -1;
    private boolean carregado = false;
    
    private PedidoFormModel pedidoForm;
    
    public AddItemPedido(PedidoFormModel pedidoForm, int index){
        this(pedidoForm);
        this.index = index;
        if(this.index >= 0 && this.index < this.pedidoForm.pedido.itens.size())
            this.initCampos();
    }
    
    /**
     * Creates new form AddItemPedido
     *
     * @param pedido
     */
    public AddItemPedido(PedidoFormModel pedidoForm) {
        this.pedidoForm = pedidoForm;
        FrameHelper.setLookAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        this.campoId.setText("");
        this.generateAddItemPedido(pedidoForm.pedido);
        AddItemPedidoHelper.initButtons(this.addItemPedido);
        AddItemPedidoHelper.initSelect(this.addItemPedido);
        this.carregado = true;
    }

    public void generateAddItemPedido(Pedido pedido) {
        this.addItemPedido = new AddItemPedidoModel();
        //this.addItemPedido.itens = pedido.itens;
        this.addItemPedido.pedido_id = pedido.id;

        this.addItemPedido.btnAdicionar = this.btnAdicionar;
        this.addItemPedido.btnCancelar = this.btnCancelar;
        this.addItemPedido.btnShowLanche = this.showLanche;

        this.addItemPedido.campoId = this.campoId;
        this.addItemPedido.campoAcrescimo = this.campoAcrescimo;
        this.addItemPedido.campoDesconto = this.campoDesconto;
        this.addItemPedido.campoModificacoes = this.campoModificacoes;
        this.addItemPedido.campoTotal = this.campoTotal;

        this.addItemPedido.selectLanche = this.selectLanche;
    }

    private boolean formIsValid(){
        if(this.selectLanche.getSelectedIndex() == 0)
            return false;
        return true;
    }
    
    private void initCampos(){
        LanchePedido lanchePedido = this.pedidoForm.pedido.itens.get(this.index);
        this.campoId.setText((lanchePedido.id == 0) ? "" : lanchePedido.id + "");
        this.campoAcrescimo.setText((lanchePedido.acrescimo + "").replace(".", ","));
        this.campoAcrescimo.setText((lanchePedido.desconto + "").replace(".", ","));
        this.campoModificacoes.setText(lanchePedido.modificacoes);
        this.selectQuantidade.setValue(lanchePedido.quantidade);
        ComboHelper.setIndex(this.selectLanche, lanchePedido.lanche_id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        selectLanche = new javax.swing.JComboBox<>();
        showLanche = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        campoDesconto = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        campoAcrescimo = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoModificacoes = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        selectQuantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 216, 220));

        jPanel2.setBackground(new java.awt.Color(207, 216, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "ID"));

        campoId.setEditable(false);
        campoId.setBackground(new java.awt.Color(255, 255, 255));
        campoId.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        campoId.setForeground(new java.awt.Color(0, 0, 0));
        campoId.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoId)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoId, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(207, 216, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lanche"));

        selectLanche.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        selectLanche.setForeground(new java.awt.Color(0, 0, 0));
        selectLanche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectLanche.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectLancheItemStateChanged(evt);
            }
        });

        showLanche.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        showLanche.setText("Mostrar dados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showLanche, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(selectLanche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(selectLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(207, 216, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Desconto*"));

        try {
            campoDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDesconto.setText("000,00");
        campoDesconto.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        campoDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDescontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDescontoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setText("R$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(campoDesconto))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(207, 216, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Acréscimo*"));

        try {
            campoAcrescimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoAcrescimo.setText("000,00");
        campoAcrescimo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        campoAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoAcrescimoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoAcrescimoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoAcrescimoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("R$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(campoAcrescimo))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(207, 216, 220));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Modificações"));

        campoModificacoes.setColumns(20);
        campoModificacoes.setRows(5);
        jScrollPane1.setViewportView(campoModificacoes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(207, 216, 220));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ações"));

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnAdicionar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(207, 216, 220));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Total"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("R$");

        campoTotal.setEditable(false);
        campoTotal.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        campoTotal.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTotal)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(207, 216, 220));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Quantidade"));

        selectQuantidade.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        selectQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        selectQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectQuantidadeStateChanged(evt);
            }
        });
        selectQuantidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectQuantidadePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectQuantidade)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectQuantidade)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if(!this.formIsValid())
            MessageHelper.createWarningMessage("Formulário inválido", "Por favor, escolha um lanche válido");
        
        LanchePedido lanchePedido = new LanchePedido();
        lanchePedido.id = (!this.campoId.getText().equals("")) ? Integer.parseInt(this.campoId.getText()) : 0;
        lanchePedido.lanche_id = ((ComboItem)this.selectLanche.getSelectedItem()).id;
        lanchePedido.acrescimo = Double.parseDouble(this.campoAcrescimo.getText().replace(",", "."));
        lanchePedido.desconto = Double.parseDouble(this.campoDesconto.getText().replace(",", "."));
        lanchePedido.modificacoes = this.campoModificacoes.getText();
        lanchePedido.quantidade = Integer.parseInt(this.selectQuantidade.getValue().toString());
        lanchePedido.valor = (new LancheDAO().get(lanchePedido.lanche_id + "")).valor * lanchePedido.quantidade;
        lanchePedido.pedido_id = this.pedidoForm.pedido.id;
        
        if(this.index != -1){
            this.pedidoForm.pedido.itens.remove(this.index);
        }
        
        this.pedidoForm.pedido.itens.add(lanchePedido);
        
        PedidoFormHelper.updatePedidoLancheTable(this.pedidoForm);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void selectQuantidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectQuantidadePropertyChange
        /*
        if(((ComboItem) this.selectLanche.getSelectedItem()).id == 0 && !this.carregado)
            return;
        double valor = new LancheDAO().get(((ComboItem)this.selectLanche.getSelectedItem()).id + "").valor;
        double acrescimo = Double.parseDouble(this.campoAcrescimo.getText().replace(",", "."));
        double desconto = Double.parseDouble(this.campoDesconto.getText().replace(",", "."));
        double total = (valor + acrescimo -desconto) * Integer.parseInt(this.selectQuantidade.getValue().toString());
        DecimalFormat decimalFormat = new DecimalFormat(",##0.00");
        this.campoTotal.setText(decimalFormat.format(total));
        */
    }//GEN-LAST:event_selectQuantidadePropertyChange

    private void selectQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectQuantidadeStateChanged
        this.updateTotalValue();
    }//GEN-LAST:event_selectQuantidadeStateChanged

    private void selectLancheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectLancheItemStateChanged
       this.updateTotalValue();
    }//GEN-LAST:event_selectLancheItemStateChanged

    private void campoDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescontoKeyPressed
        this.updateTotalValue();
    }//GEN-LAST:event_campoDescontoKeyPressed

    private void campoDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescontoKeyReleased
        this.updateTotalValue();
    }//GEN-LAST:event_campoDescontoKeyReleased

    private void campoDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescontoKeyTyped
        this.updateTotalValue();
    }//GEN-LAST:event_campoDescontoKeyTyped

    private void campoAcrescimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAcrescimoKeyPressed
        this.updateTotalValue();
    }//GEN-LAST:event_campoAcrescimoKeyPressed

    private void campoAcrescimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAcrescimoKeyReleased
        this.updateTotalValue();
    }//GEN-LAST:event_campoAcrescimoKeyReleased

    private void campoAcrescimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAcrescimoKeyTyped
        this.updateTotalValue();
    }//GEN-LAST:event_campoAcrescimoKeyTyped

    private void updateTotalValue(){
        double valor;
        
        if(this.carregado){
            if(((ComboItem)this.selectLanche.getSelectedItem()).id == 0)
                valor = 0;
            else
                valor = new LancheDAO().get(((ComboItem)this.selectLanche.getSelectedItem()).id + "").valor;
        }else{
            valor = 0;
        }
        
            
        double acrescimo = Double.parseDouble(this.campoAcrescimo.getText().replace(",", "."));
        double desconto = Double.parseDouble(this.campoDesconto.getText().replace(",", "."));
        double total = (valor + acrescimo -desconto) * Integer.parseInt(this.selectQuantidade.getValue().toString());
        DecimalFormat decimalFormat = new DecimalFormat(",##0.00");
        this.campoTotal.setText(decimalFormat.format(total));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemPedido(new PedidoFormModel()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JFormattedTextField campoAcrescimo;
    private javax.swing.JFormattedTextField campoDesconto;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextArea campoModificacoes;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectLanche;
    private javax.swing.JSpinner selectQuantidade;
    private javax.swing.JButton showLanche;
    // End of variables declaration//GEN-END:variables
}
